# src/config.py

# --- Screen ---
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# --- Arena ---
ARENA_WIDTH = 2000
ARENA_HEIGHT = 2000

# --- Player ---
PLAYER_SPEED = 3.0
PLAYER_HP = 100
PLAYER_ATTACK_RANGE = 60.0
PLAYER_ATTACK_DAMAGE = 25
PLAYER_ATTACK_COOLDOWN = 30  # ticks
PLAYER_SIZE = 16.0  # collision radius
PLAYER_INVINCIBILITY_TICKS = 30

# --- Enemies ---
SWARMER_SPEED = 2.5
SWARMER_HP = 30
SWARMER_CONTACT_DAMAGE = 5
SWARMER_SIZE = 10.0

TANK_SPEED = 1.0
TANK_HP = 150
TANK_CONTACT_DAMAGE = 15
TANK_SIZE = 20.0

SHOOTER_SPEED = 1.5
SHOOTER_HP = 50
SHOOTER_CONTACT_DAMAGE = 5
SHOOTER_SIZE = 14.0
SHOOTER_FIRE_RANGE = 200.0
SHOOTER_FIRE_COOLDOWN = 60  # ticks

# --- Projectiles ---
PROJECTILE_SPEED = 4.0
PROJECTILE_DAMAGE = 10
PROJECTILE_SIZE = 5.0
PROJECTILE_LIFETIME = 180  # ticks before despawn

# --- Pickups ---
HEALTH_PICKUP_HEAL = 25
XP_PICKUP_VALUE = 10
PICKUP_SIZE = 8.0
PICKUP_DROP_CHANCE = 0.3  # 30% chance enemy drops a pickup on death

# --- Waves ---
WAVE_INTERVAL = 300  # ticks between waves
INITIAL_ENEMIES_PER_WAVE = 5
ENEMIES_PER_WAVE_INCREASE = 2

# --- LLM ---
OLLAMA_URL = "http://localhost:11434"
OLLAMA_MODEL = "llama3.1:8b"
LLM_TEMPERATURE = 0.3
LLM_NUM_PREDICT = 100
